### ISSUE TITLE
Add GitHub Action for lint, prettier, build

### ISSUE THREAD

**Issue by khattakdev** [EddieJaoudeCommunity/api#15]
This issue is a subtask of #12

**Comment by eddiejaoude** [comment]
I also added the trigger event for `push`

**Comment by khattakdev** [comment]
> I also added the trigger event for `push`

Do we need it for `push`? We are concern about the `main` branch only, so we care about the code that is in that branch (only).

**Comment by eddiejaoude** [comment]
When pushing to our feature branches, it can be good to know if something is broken before a PR is raised. 

I will make `main` a protect branch.
